services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keystone
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    restart: unless-stopped
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json

volumes:
  pgdata:

configs:
  pgpass:
    content: db:5432:*:admin:root
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "Postgres",
        "Host": "db",
        "Port": 5432,
        "MaintenanceDB": "keystone",
        "Username": "admin",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}
